[app]

# (required) Title of your application
title = Media Catcher

# (required) Package name
package.name = mediacatcher

# (required) Package domain (usually follows reverse domain name notation)
package.domain = com.markusaureus

# (required) Source code where the main.py lives
source.dir = .

# (required) Name of the main py file
source.main_py = main.py

# (optional) Filename to be used for the icon of the application.
icon.filename = %(source.dir)s/icon-512x512.png

# (optional) Presplash of the application.
presplash.filename = %(source.dir)s/presplash_screen.png

# (required) Version of your application
version = 1.0

# (required) List of requirements
# Kivy sa pridá automaticky. Pridali sme yt-dlp.
requirements = python3, kivy, yt-dlp, pyjnius, android

# (optional) Application orientation
# "portrait", "landscape", "all"
orientation = portrait

# (optional) Make the application fullscreen.
fullscreen = 0

# (optional) List of Android permissions
android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE


[buildozer]

# (int) Log level (0 = error, 1 = info, 2 = debug (very verbose))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# -------------------------------------------------------------------
# ---- The rest of the file can be left at its default values. ----
# -------------------------------------------------------------------

# (list) List of available targets, default is everything
#available_targets = android,ios

# (str) Default target to use, can be overridden by the command line
#default_target = android

# (str) Name of the executable generated by the pur
# executable_name = mediacatcher

# (str) Path to build C source code, default to ./.buildozer/c_code
# c_code_path =

# (str) The directory in which python-for-android will be cloned
# p4a.source_dir =

(str) The directory in which python-for-android will be cloned
p4a.branch = master

# (str) python-for-android fork to use, defaults to the official repo
# p4a.fork = kivy

# (str) The directory in which python-for-android will be cloned
# p4a.url =

# (str) The directory in which the android SDK will be downloaded
# android.sdk_path =

# (str) The directory in which the android NDK will be downloaded
# android.ndk_path =

# (str) The directory in which the android ANT will be downloaded
# android.ant_path =

# (str) python-for-android git clone directory (if you use your own fork)
# p4a.local_recipes =

# (str) The Android archs to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.archs = arm64-v8a, armeabi-v7a

# (int) Android API to use
android.api = 31

# (int) Minimum API required
android.minapi = 21

# (int) Android SDK version to use
android.sdk = 24

# (str) Android NDK version to use
android.ndk = 25b

# (str) Android NDK path. If not set, buildozer will download it.
# android.ndk_path =

# (str) Android ANT path. If not set, buildozer will download it.
# android.ant_path =

# (bool) Copy library files to project (useful for debugging)
# android.copy_libs = 1

# (str) The Android M permissions
# (see https://python-for-android.readthedocs.io/en/latest/services/#android-m-permissions)
# android.permissions = INTERNET

# (list) same as [app] requirements, used often for partial builds
# android.requirements =

# (str) Custom source folders for requirements
# android.recipe_dirs =

# (str) The name of the android entry point, default is org.kivy.android.PythonActivity
# android.entrypoint =

# (str) Android app theme, default is "@android:style/Theme.NoTitleBar"
# android.theme =

# (list) Pattern to whitelist for the whole project
# android.whitelist =

# (str) Path to a custom rules.xml file
# android.custom_rules =

# (str) Path to a custom AndroidManifest.xml to merge with p4a's
# android.manifest.template =

# (str) Path to a custom main.xml to merge with p4a's
# android.mainline_template =

# (str) Path to a custom AndroidManifest.xml to merge with p4a's
# android.manifest.addition =

# (str) Path to a custom main.xml to merge with p4a's
# android.mainline_addition =

# (list) XML files to add to the AndroidManifest.xml
# android.manifest.xml_additions =

# (list) Java files to add to the android project
# android.add_jars =

# (list) Java files to add to the android project
# android.add_src =

# (list) Gradle dependencies to add to the android project
# android.add_gradle_dependencies =

# (list) AAR files to add to the android project
# android.add_aars =

# (bool) If a splash screen should be displayed
# android.presplash_lottie =

# (str) Lottie animation file to show in presplash
# android.presplash_lottie_file =

# (bool) Whether to build the application as an Android App Bundle (AAB)
# android.aab =

# (bool) Whether to build the application as an Android App Bundle (AAB)
# android.aab_universal_apk =

# (str) Keystore path
# android.keystore.path =

# (str) Keystore alias
# android.keystore.alias =

# (str) Keystore password
# android.keystore.password =

# (str) Key password
# android.keystore.key.password =

# (bool) If release signed, default is False
# android.release_artifact =

# (str) Specifies the type of file to generate.
# see https://developer.android.com/studio/build/build-variants
# android.build_type =

# (list) Garden requirements
# garden.requirements =

# (str) The directory in which python-for-android will be cloned
# garden.source_dir =

# (str) The directory in which python-for-android will be cloned
# garden.branch = master

# (str) python-for-android fork to use, defaults to the official repo
# garden.fork = kivy

# (str) The directory in which python-for-android will be cloned
# garden.url =

# (list) List of available targets, default is everything
# available_targets = android

# (str) Default target to use, can be overridden by the command line
# default_target = android
